name: Release menu

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker HUB
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-menu
        uses: docker/metadata-action@v3
        with:
          images: cciobanu98/menu-service

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: backend/Services/Menu/Menu.Api/Dockerfile
          context: backend
          push: true
          tags: ${{ steps.meta-menu.outputs.tags }}
          labels: ${{ steps.meta-menu.outputs.labels }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-order
        uses: docker/metadata-action@v3
        with:
          images: cciobanu98/order-service

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: backend/Services/Order/Order.Api/Dockerfile
          context: backend
          push: true
          tags: ${{ steps.meta-order.outputs.tags }}
          labels: ${{ steps.meta-order.outputs.labels }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-users
        uses: docker/metadata-action@v3
        with:
          images: cciobanu98/users-service

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: backend/Services/Users.Api/Dockerfile
          context: backend
          push: true
          tags: ${{ steps.meta-users.outputs.tags }}
          labels: ${{ steps.meta-users.outputs.labels }}

      - name: Publish helm menu chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: deployment
